version: "3.8"
services:
  edge:
    image: ghcr.io/voltaire/render-controller/edge:latest
    restart: unless-stopped
    init: true
    env_file: ./prod.env
    logging:
      driver: awslogs
      options:
        awslogs-group: render-controller/edge
        awslogs-create-group: "true"
        awslogs-region: "us-west-2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  caddy:
    build:
      context: ./caddy
    depends_on:
      - edge
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-group: render-controller/caddy
        awslogs-create-group: "true"
        awslogs-region: "us-west-2"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
