on:
  push:
    branches:
      - main
  pull_request:
    branches:
name: build and push
jobs:
  pipeline:
    strategy:
      matrix:
        go-version: [1.15.5]
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout code
        uses: actions/checkout@v2
      - name: test
        run: go test -v -race ./...
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker
        uses: docker/setup-buildx-action@v1
      - name: login to github docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: docker build and push
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.ref }}
      - name: docker build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - name: notify renderer
        if: github.ref == 'refs/heads/main'
        uses: bsdlp/notify-docker-pull@34767059efa90abbaf8cd04d68a3ea79be10857e
        with:
          server_url: "https://renderer.tonkat.su"
          image: ghcr.io/${{ github.repository }}:latest
          private_key: ${{ secrets.UPDATE_DOCKER_IMAGE_PRIVATE_KEY }}
